Jdp210202 19
piotr-grosicki/project-jdp-2102-02 pull request #16
Opened 2021-03-04 23:11 UTC by PiotrSzpara

2021-03-06 09:21 UTC, piotr-grosicki requested changes
konflikty

2021-03-06 17:13 UTC, piotr-grosicki requested changes
do usuniecia junit5 + testy usuwania

2021-03-09 17:20 UTC, sebalaka commented
![image](https://user-images.githubusercontent.com/17243919/110511034-1a897380-8104-11eb-9aff-af4880fca22e.png)
Konflikt w Cart

2021-03-10 10:05 UTC, kris33293 approved these changes

2021-03-10 18:22 UTC, sebalaka approved these changes

2021-03-10 20:40 UTC, piotr-grosicki approved these changes

2021-03-10 20:42 UTC, merged