Jdp210202 20
piotr-grosicki/project-jdp-2102-02 pull request #17
Opened 2021-03-05 20:02 UTC by MichalZolkiewicz

2021-03-06 09:21 UTC, piotr-grosicki requested changes

2021-03-06 09:21 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserTest.java
> +public class UserTest {
brakuje testow usuwania

2021-03-08 20:07 UTC, adam-stan approved these changes

2021-03-09 17:16 UTC, sebalaka approved these changes

2021-03-10 13:06 UTC, sebalaka commented
![image](https://user-images.githubusercontent.com/17243919/110634074-d51f8180-81a9-11eb-8b5c-34e8ae1eb720.png)

chyba trza szybciej mergowac 🍡

2021-03-10 20:40 UTC, piotr-grosicki approved these changes

2021-03-10 21:42 UTC, merged