Jdp210202 17
piotr-grosicki/project-jdp-2102-02 pull request #18
Opened 2021-03-06 16:23 UTC by kris33293

2021-03-06 17:04 UTC, piotr-grosicki requested changes
konflikty

2021-03-06 17:08 UTC, piotr-grosicki requested changes

2021-03-06 17:08 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/ProductDaoTests.java
> +public class ProductDaoTests {
brakuje testow usuwania + sprawdzenia co sie dzieje przy usunieciu z relacjami

2021-03-08 17:16 UTC, kris33293 commented
ktos ma pomysl na sprawdzenie co sie dzieje  z relacjami przy usunieciu?

2021-03-08 18:18 UTC, kris33293 commented
wyglada na to ze przy usunieciu produktu usuwa tez jego relacje (user, order, cart...)

2021-03-09 21:28 UTC, PiotrSzpara approved these changes
Wygląda OK

2021-03-10 13:05 UTC, sebalaka approved these changes

2021-03-10 20:41 UTC, piotr-grosicki approved these changes

2021-03-11 16:09 UTC, merged