Jdp210202 34
piotr-grosicki/project-jdp-2102-02 pull request #19
Opened 2021-03-06 22:51 UTC by PiotrSzpara

Entities unification.

2021-03-07 07:42 UTC, sebalaka reviewed
Konflikty w group i order 

![image](https://user-images.githubusercontent.com/17243919/110232894-f883cb80-7f20-11eb-86ab-d1a1aa30848f.png)

2021-03-07 20:17 UTC, kris33293 commented
konflikty chyba tak i tak beda bo kazdy musi je u siebie naprawic?

2021-03-07 20:47 UTC, piotr-grosicki requested changes
Nie. Konfliktow nie moze byc na tym branchu bo sie nie zmerguje do maina. Konflikty tutaj sa poniewaz osoba wystawiajaca PR nie zrobila branchy z najnowszego main :)

2021-03-08 07:57 UTC, sebalaka approved these changes
co prawda nwm po co zmiany z longa na inta, ale no wyglada oki teraz

2021-03-08 09:49 UTC, kris33293 approved these changes

2021-03-08 09:56 UTC, piotr-grosicki approved these changes

2021-03-08 09:57 UTC, merged