Create order tests
piotr-grosicki/project-jdp-2102-02 pull request #32
Opened 2021-03-13 09:55 UTC by Mikolajczyk-Kamil

2021-03-13 11:26 UTC, MichalZolkiewicz commented on src/test/java/com/kodilla/ecommercee/domain/OrderTestSuite.java
> +    }*/
Zostawiłeś to zakomentowane, a ten Optional nie śmiga bo masz w OrderDao napisaną metodę findById i ona zwraca Order a nie Optional. Jak to usuniesz z OrderDao to powinno śmigać.

2021-03-13 16:45 UTC, sebalaka commented
![image](https://user-images.githubusercontent.com/17243919/111037332-d8be3d00-8423-11eb-8008-e382647070cd.png)

pull z maina potrzebny - konflikty

2021-03-13 20:34 UTC, kris33293 approved these changes

2021-03-13 20:35 UTC, kris33293 requested changes
pull z maina a tak to wszystko ok

2021-03-13 22:01 UTC, PiotrSzpara reviewed
Order ma jeszcze relacje z Product. Można by taki test tu zrobić.

2021-03-14 12:00 UTC, kris33293 approved these changes

2021-03-14 13:19 UTC, MichalZolkiewicz approved these changes

2021-03-14 13:24 UTC, merged