Jdp210202 1
piotr-grosicki/project-jdp-2102-02 pull request #4
Opened 2021-02-26 16:28 UTC by MichalZolkiewicz

2021-02-26 19:56 UTC, sebalaka commented on src/main/java/com/kodilla/ecommercee/ProductDto.java
> +@Getter
moze dajmy @Data , to bedziemy miec setter getter tostring itd, nwm

2021-02-26 22:32 UTC, PiotrSzpara commented on src/main/java/com/kodilla/ecommercee/ProductDto.java
> +    String description;
Myślę, że dobrze by było trzymać się konwencji nazewnictwa jak przy productId i productName czyli: productPrice i productDescription

2021-02-28 08:51 UTC, piotr-grosicki requested changes
konflikty do poprawienia

2021-02-28 10:15 UTC, sebalaka approved these changes

2021-03-01 09:10 UTC, piotr-grosicki approved these changes

2021-03-01 09:10 UTC, merged