Jdp210202 12 - ready to review
piotr-grosicki/project-jdp-2102-02 pull request #8
Opened 2021-02-27 21:55 UTC by PiotrSzpara

2021-02-28 08:58 UTC, piotr-grosicki requested changes

2021-02-28 08:58 UTC, piotr-grosicki commented on .gitignore
> +src/main/resources/application.properties
ten plik oczywiscie powinien byc na gicie i nie powinien zostac dodany do git ignore

2021-02-28 08:58 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +server.port=9090
dlaczego port zostal zmieniony? powinien zostac 8080 tak zeby nie psuc pracy innym uczestnikom projektu

2021-02-28 16:15 UTC, PiotrSzpara commented on .gitignore
> +src/main/resources/application.properties
OK

2021-02-28 16:17 UTC, PiotrSzpara commented on src/main/resources/application.properties
> +server.port=9090
OK. 
zmieniłem port bo miałem jakiś 8080 miał jakiś konflikt na moim komputerze.

2021-03-01 09:12 UTC, piotr-grosicki approved these changes

2021-03-01 09:12 UTC, merged